apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Mongodb Server deployment"; while ! nc -z mongodb 27017; do sleep 1; printf "-"; done; echo -e "  >> Mongo DB Server has started";']      
     
      containers:
      - name: test-app
        image: aaarpitaaa/webappimage:latest
        volumeMounts:
          - name: shared-logs
            mountPath: /var/log/
        env:
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        ports:
        - containerPort: 5000
          name: web-port
      - name: sidecar-container
        image: busybox
        command: ["sh","-c","while true; do cat /var/log/sidecar.log; sleep 30; done"]
        volumeMounts:
          - name: shared-logs
            mountPath: /var/log/
      volumes:
      - name: shared-logs
        emptyDir: {} 
        livenessProbe:
          exec:
            command: 
             - /bin/sh
             - c
             - nc -z test 5000
          initialDelaySeconds: 60
          periodSeconds: 10

